import subprocess

print 'survey_processing.py'
subprocess.call(['python', 'survey_processing.py'])
print 'merge_files.py'
subprocess.call(['python', 'merge_files.py'])
print 'new_attributes.py'
subprocess.call(['python', 'new_attributes.py'])
print 'visualize.py'
subprocess.call(['python', 'visualize.py'])
print 'gower.R'
subprocess.call(['Rscript', 'gower.R'])
print 'matrix1n2.py'
subprocess.call(['python', 'matrix1n2.py'])
print 'part_clust.py'
subprocess.call(['python', 'part_clust.py'])
print 'visualize2.R'
subprocess.call(['Rscript', 'visualize2.R'])
print 'silplot.R'
subprocess.call(['Rscript', 'silplot.R'])
print 'piechart.py'
subprocess.call(['python', 'piechart.py'])
print 'barplot.R'
subprocess.call(['Rscript', 'barplot.R'])